// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string leaderboard_beach__level_6 = "CgkI-8Oml4oOEAIQXg"; // <GPGSID>
        public const string leaderboard_beach__level_2 = "CgkI-8Oml4oOEAIQWg"; // <GPGSID>
        public const string achievement_window_shopper = "CgkI-8Oml4oOEAIQGQ"; // <GPGSID>
        public const string achievement_monster_mayhem = "CgkI-8Oml4oOEAIQGA"; // <GPGSID>
        public const string leaderboard_underwater__level_9 = "CgkI-8Oml4oOEAIQTg"; // <GPGSID>
        public const string leaderboard_underwater__level_8 = "CgkI-8Oml4oOEAIQTQ"; // <GPGSID>
        public const string leaderboard_desert__level_9 = "CgkI-8Oml4oOEAIQPA"; // <GPGSID>
        public const string leaderboard_desert__level_8 = "CgkI-8Oml4oOEAIQOw"; // <GPGSID>
        public const string leaderboard_beach__level_4 = "CgkI-8Oml4oOEAIQXA"; // <GPGSID>
        public const string leaderboard_underwater__level_3 = "CgkI-8Oml4oOEAIQSA"; // <GPGSID>
        public const string leaderboard_underwater__level_2 = "CgkI-8Oml4oOEAIQRw"; // <GPGSID>
        public const string leaderboard_underwater__level_1 = "CgkI-8Oml4oOEAIQRg"; // <GPGSID>
        public const string achievement_rolling_rich = "CgkI-8Oml4oOEAIQDg"; // <GPGSID>
        public const string leaderboard_underwater__level_6 = "CgkI-8Oml4oOEAIQSw"; // <GPGSID>
        public const string achievement_first_fortune = "CgkI-8Oml4oOEAIQDA"; // <GPGSID>
        public const string leaderboard_desert__level_2 = "CgkI-8Oml4oOEAIQNQ"; // <GPGSID>
        public const string leaderboard_desert__level_5 = "CgkI-8Oml4oOEAIQOA"; // <GPGSID>
        public const string leaderboard_desert__level_4 = "CgkI-8Oml4oOEAIQNw"; // <GPGSID>
        public const string leaderboard_desert__level_7 = "CgkI-8Oml4oOEAIQOg"; // <GPGSID>
        public const string leaderboard_desert__level_6 = "CgkI-8Oml4oOEAIQOQ"; // <GPGSID>
        public const string leaderboard_underwater__level_7 = "CgkI-8Oml4oOEAIQTA"; // <GPGSID>
        public const string achievement_snow_breaker = "CgkI-8Oml4oOEAIQFw"; // <GPGSID>
        public const string leaderboard_beach__level_8 = "CgkI-8Oml4oOEAIQMw"; // <GPGSID>
        public const string achievement_rising_roller = "CgkI-8Oml4oOEAIQJw"; // <GPGSID>
        public const string leaderboard_desert__level_3 = "CgkI-8Oml4oOEAIQNg"; // <GPGSID>
        public const string leaderboard_beach__level_3 = "CgkI-8Oml4oOEAIQWw"; // <GPGSID>
        public const string achievement_beach_trophy = "CgkI-8Oml4oOEAIQIQ"; // <GPGSID>
        public const string leaderboard_forest__level_3 = "CgkI-8Oml4oOEAIQPw"; // <GPGSID>
        public const string leaderboard_ice__level_7 = "CgkI-8Oml4oOEAIQVQ"; // <GPGSID>
        public const string leaderboard_underwater__level_4 = "CgkI-8Oml4oOEAIQSQ"; // <GPGSID>
        public const string leaderboard_underwater__level_5 = "CgkI-8Oml4oOEAIQSg"; // <GPGSID>
        public const string achievement_ice_trophy = "CgkI-8Oml4oOEAIQJQ"; // <GPGSID>
        public const string achievement_deep_diver = "CgkI-8Oml4oOEAIQHw"; // <GPGSID>
        public const string achievement_desert_trophy = "CgkI-8Oml4oOEAIQIw"; // <GPGSID>
        public const string achievement_star_legend = "CgkI-8Oml4oOEAIQEg"; // <GPGSID>
        public const string achievement_first_roll = "CgkI-8Oml4oOEAIQBw"; // <GPGSID>
        public const string achievement_coin_collector = "CgkI-8Oml4oOEAIQDQ"; // <GPGSID>
        public const string leaderboard_ice__level_4 = "CgkI-8Oml4oOEAIQUg"; // <GPGSID>
        public const string achievement_beach_explorer = "CgkI-8Oml4oOEAIQHA"; // <GPGSID>
        public const string leaderboard_ice__level_3 = "CgkI-8Oml4oOEAIQUQ"; // <GPGSID>
        public const string achievement_getting_serious = "CgkI-8Oml4oOEAIQCA"; // <GPGSID>
        public const string achievement_desert_survivor = "CgkI-8Oml4oOEAIQHg"; // <GPGSID>
        public const string achievement_arachnophobia = "CgkI-8Oml4oOEAIQFA"; // <GPGSID>
        public const string achievement_star_rookie = "CgkI-8Oml4oOEAIQEA"; // <GPGSID>
        public const string leaderboard_beach__level_5 = "CgkI-8Oml4oOEAIQXQ"; // <GPGSID>
        public const string achievement_hardcore_roller = "CgkI-8Oml4oOEAIQKg"; // <GPGSID>
        public const string achievement_halfway_there = "CgkI-8Oml4oOEAIQCg"; // <GPGSID>
        public const string achievement_fearless_roller = "CgkI-8Oml4oOEAIQKQ"; // <GPGSID>
        public const string leaderboard_beach__level_1 = "CgkI-8Oml4oOEAIQWQ"; // <GPGSID>
        public const string leaderboard_ice__level_8 = "CgkI-8Oml4oOEAIQVg"; // <GPGSID>
        public const string leaderboard_ice__level_2 = "CgkI-8Oml4oOEAIQUA"; // <GPGSID>
        public const string achievement_ultimate_roller = "CgkI-8Oml4oOEAIQJg"; // <GPGSID>
        public const string leaderboard_beach__level_9 = "CgkI-8Oml4oOEAIQMg"; // <GPGSID>
        public const string leaderboard_forest__level_9 = "CgkI-8Oml4oOEAIQRQ"; // <GPGSID>
        public const string leaderboard_forest__level_8 = "CgkI-8Oml4oOEAIQRA"; // <GPGSID>
        public const string achievement_star_pro = "CgkI-8Oml4oOEAIQEQ"; // <GPGSID>
        public const string leaderboard_desert__level_1 = "CgkI-8Oml4oOEAIQNA"; // <GPGSID>
        public const string leaderboard_beach__level_7 = "CgkI-8Oml4oOEAIQXw"; // <GPGSID>
        public const string leaderboard_forest__level_2 = "CgkI-8Oml4oOEAIQPg"; // <GPGSID>
        public const string leaderboard_forest__level_1 = "CgkI-8Oml4oOEAIQPQ"; // <GPGSID>
        public const string leaderboard_ice__level_6 = "CgkI-8Oml4oOEAIQVA"; // <GPGSID>
        public const string leaderboard_forest__level_7 = "CgkI-8Oml4oOEAIQQw"; // <GPGSID>
        public const string achievement_hardheaded = "CgkI-8Oml4oOEAIQKA"; // <GPGSID>
        public const string leaderboard_forest__level_5 = "CgkI-8Oml4oOEAIQQQ"; // <GPGSID>
        public const string leaderboard_forest__level_4 = "CgkI-8Oml4oOEAIQQA"; // <GPGSID>
        public const string achievement_crab_crusher = "CgkI-8Oml4oOEAIQEw"; // <GPGSID>
        public const string achievement_jelly_hunter = "CgkI-8Oml4oOEAIQFg"; // <GPGSID>
        public const string leaderboard_ice__level_5 = "CgkI-8Oml4oOEAIQUw"; // <GPGSID>
        public const string achievement_roll_master = "CgkI-8Oml4oOEAIQCQ"; // <GPGSID>
        public const string leaderboard_ice__level_1 = "CgkI-8Oml4oOEAIQTw"; // <GPGSID>
        public const string leaderboard_ice__level_9 = "CgkI-8Oml4oOEAIQVw"; // <GPGSID>
        public const string achievement_forest_trophy = "CgkI-8Oml4oOEAIQIg"; // <GPGSID>
        public const string leaderboard_forest__level_6 = "CgkI-8Oml4oOEAIQQg"; // <GPGSID>
        public const string achievement_ice_breaker = "CgkI-8Oml4oOEAIQIA"; // <GPGSID>
        public const string achievement_underwater_trophy = "CgkI-8Oml4oOEAIQJA"; // <GPGSID>
        public const string achievement_style_roller = "CgkI-8Oml4oOEAIQGg"; // <GPGSID>
        public const string achievement_scorpion_slayer = "CgkI-8Oml4oOEAIQFQ"; // <GPGSID>
        public const string achievement_forest_runner = "CgkI-8Oml4oOEAIQHQ"; // <GPGSID>
        public const string achievement_fashion_icon = "CgkI-8Oml4oOEAIQGw"; // <GPGSID>

}

